# language: python
# python:
#   - "3.7"
# # command to install dependencies
# install:
#   - pip install -r requirements.txt
# # command to run tests
# script:
#   - SECRET_KEY="whatever" ./manage.py test

language: python
python:
  - "3.7.3"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test
